### ISSUE TITLE
[ALFA] (US 9) Tela de Listagem e Detalhamento do Grupo de Pesquisa

### ISSUE THREAD

**Issue by mattd-silva22** [MATE85-UFBA/IC045-marketplace-ufba#26]
### Tela de Listagem e Detalhamento do Grupo de Pesquisa

**Como usuário**, eu quero visualizar os grupos de pesquisa.
**Como pesquisador**, eu quero visualizar os grupos de pesquisa que pertenço.

#### Descrição
Esta issue tem como objetivo desenvolver a tela de de Listagem e Detalhamento do Grupo de Pesquisa com base no protótipo fornecido no Figma. A versão inicial pode ser construída utilizando dados mockados, caso o backend ainda não esteja disponível.

#### Tarefas

- [ ] Implementar a tela seguindo o layout do protótipo no Figma.
- [ ] Desenvolver a versão inicial já considerando responsividade para diferentes dispositivos.
- [ ] Utilizar dados mockados se o módulo do backend ainda não estiver pronto.
- [ ] Criar testes simples para garantir que os principais componentes sejam renderizados corretamente na tela.

#### Critérios de Aceitação:

- [ ] O sistema deve apresentar uma lista de todos os grupos de pesquisa. [prioridade alta]
- [ ] O sistema deve permitir filtrar os grupos de pesquisa (nome, área de conhecimento). [prioridade alta]
- [ ] Quando o usuário clicar em um grupo de pesquisa, será apresentada uma tela que listará projetos e outra que listará membros. [prioridade alta]
- [ ] O sistema deve permitir filtrar os grupos de pesquisa pelas palavras-chave dos projetos desenvolvidos pelo grupo. [prioridade baixa]
- [ ] O sistema deve permitir adicionar membros ao grupo (pesquisadores e alunos) (members). [prioridade baixa]
- [ ] O sistema deve permitir que o líder passe a liderança do grupo de pesquisa para outro pesquisador (leader, researcherId). [prioridade baixa]

#### Atributos das Tabela ResearchGroup

```
model ResearchGroup {
  id             String          @id @default(uuid())
  name           String          @unique
  description    String
  urlCNPQ        String?
  img            String?
  leader         Researcher      @relation(fields: [researcherId], references: [userId], name: "ResearchGroupLeader")
  researcherId   String
  knowledgeAreas KnowledgeArea[]
  members        Researcher[]    @relation("ResearchGroupMembers")
  projects       Project[]
  createdAt      DateTime        @default(now())
  updatedAt      DateTime        @updatedAt
  Notifications  Notification[]
}

model Researcher {
  user                   User            @relation(fields: [userId], references: [id])
  userId                 String          @id
  urlLattes              String?
  researcherType         ResearcherType  @default(TEACHER)
  researchGroupsAsLeader ResearchGroup[] @relation("ResearchGroupLeader")
  researchGroupsAsMember ResearchGroup[] @relation("ResearchGroupMembers")
  createdAt              DateTime        @default(now())
  updatedAt              DateTime        @updatedAt
}

model Project {
  id              String        @id @default(uuid())
  name            String
  started_at      DateTime
  finished_at     DateTime?
  researchGroup   ResearchGroup @relation(fields: [researchGroupId], references: [id])
  researchGroupId String
  demand          Demand?       @relation(fields: [demandId], references: [id])
  demandId        String?
  keywords        Keyword[]
  createdAt       DateTime      @default(now())
  updatedAt       DateTime      @updatedAt
}

```

**Comment by felipejrvieira** [comment]
### Detalhamento de Grupo de Pesquisa - Lista de Membros
![Detalhamento de Grupo de Pesquisa - Lista de Membros](https://github.com/user-attachments/assets/86aa73d3-b424-4b94-a5fc-e72e7f171743)

### Detalhamento de Grupo de Pesquisa - Lista de Projetos
![Detalhamento de Grupo de Pesquisa - Lista de Projetos](https://github.com/user-attachments/assets/c7a6be69-5447-405c-bb23-dffa54d6883f)
