### ISSUE TITLE
[ALFA] (US 8) CRUD Grupo de Pesquisas

### ISSUE THREAD

**Issue by mattd-silva22** [MATE85-UFBA/IC045-marketplace-ufba#31]
### Desenvolvimento do Módulo de CRUD de Grupo de Pesquisas

**Como pesquisador**, eu quero cadastrar um novo grupo de pesquisa.

#### Tarefas

- [x] Criar o módulo `ResearchGroup` no NestJS.
- [x] Desenvolver os endpoints para as operações de CRUD (Create, Read, Update, Delete):
  - [x] `POST /researchgroups`: Criar uma novo ResearchGroup.
  - [x] `GET /researchgroups`: Listar todos os ResearchGroup.
  - [x] `GET /researchgroups/:id`: Obter um ResearchGroup por ID.
  - [x] `PUT /researchgroups/:id`: Atualizar um ResearchGroup existente.
  - [x] `DELETE /researchgroups/:id`: Deletar um ResearchGroup por ID.
- [x] Criar serviços e repositórios necessários para manipular os dados no banco.
- [x] Implementar testes simples de integração para cada funcionalidade do módulo.

#### Extras
- [x] Testes Unitários para funcionalidade

#### Critérios de Aceitação:

- [x] O sistema deve permitir o cadastro de um name, description, urlCNPQ, img para o grupo. [prioridade alta]
- [ ] O sistema deve permitir a seleção de uma ou mais áreas de conhecimento (knowledgeAreas) para o grupo. [prioridade alta]
- [ ] O sistema deve registrar o pesquisador que criou o grupo como líder (leader, researcherId). [prioridade alta]
- [ ] O sistema deve permitir adicionar membros ao grupo (pesquisadores e alunos) (members). [prioridade baixa]
- [ ] O sistema deve permitir que o líder passe a liderança do grupo de pesquisa para outro pesquisador (leader, researcherId). [prioridade baixa]]

#### Atributos das Tabela ResearchGroup

```
model ResearchGroup {
  id             String          @id @default(uuid())
  name           String          @unique
  description    String
  urlCNPQ        String?
  img            String?
  leader         Researcher      @relation(fields: [researcherId], references: [userId], name: "ResearchGroupLeader")
  researcherId   String
  knowledgeAreas KnowledgeArea[]
  members        Researcher[]    @relation("ResearchGroupMembers")
  projects       Project[]
  createdAt      DateTime        @default(now())
  updatedAt      DateTime        @updatedAt
  Notifications  Notification[]
}
```

**Comment by felipejrvieira** [comment]
[] Fazer com que a listagem de todos os grupos de pesquisa retorne de forma paginada.
