### ISSUE TITLE
[ALFA] (US 8) Tela de Cadastrar Grupo de Pesquisa

### ISSUE THREAD

**Issue by erreip-m** [MATE85-UFBA/IC045-marketplace-ufba#64]
### Tela de "Cadastrar Grupo de Pesquisa"

**Como pesquisador**, eu quero cadastrar um novo grupo de pesquisa.

#### Descrição

Esta issue tem como objetivo desenvolver a tela de "Cadastrar Grupo de Pesquisa" com base no protótipo fornecido no Figma. A versão inicial pode ser construída utilizando dados mockados, caso o backend ainda não esteja disponível.

#### Tarefas

- [ ]  Implementar a tela seguindo o layout do protótipo no Figma.
- [ ]  Desenvolver a versão inicial já considerando responsividade para diferentes dispositivos.
- [ ]  Utilizar dados mockados se o módulo do backend ainda não estiver pronto.
- [ ]  Criar testes simples para garantir que os principais componentes sejam renderizados corretamente na tela.

#### Critérios de Aceitação:

- [ ] O sistema deve permitir o cadastro de um name, description, urlCNPQ, img para o grupo. [prioridade alta]
- [ ] O sistema deve permitir a seleção de uma ou mais áreas de conhecimento (knowledgeAreas) para o grupo. [prioridade alta]
- [ ] O sistema deve registrar o pesquisador que criou o grupo como líder (leader, researcherId). [prioridade alta]

#### Atributos das Tabela ResearchGroup

```
model ResearchGroup {
  id             String          @id @default(uuid())
  name           String          @unique
  description    String
  urlCNPQ        String?
  img            String?
  leader         Researcher      @relation(fields: [researcherId], references: [userId], name: "ResearchGroupLeader")
  researcherId   String
  knowledgeAreas KnowledgeArea[]
  members        Researcher[]    @relation("ResearchGroupMembers")
  projects       Project[]
  createdAt      DateTime        @default(now())
  updatedAt      DateTime        @updatedAt
  Notifications  Notification[]
}
```

**Comment by felipejrvieira** [comment]
![Tela de cadastro de Grupo de Pesquisa](https://github.com/user-attachments/assets/37eaaab5-06c7-48e1-89f3-ba4f172fad5f)
O protótipo da tela ainda está incompleto, faltando os seguintes campos:
-  `urlCNPQ` para colocar o link referente ao cadastro oficial do grupo de pesquisa.
- `researcherId` para indicar quem é o líder do grupo. Esse campo já virá preenchido com o nome do pesquisador que está cadastrando o grupo de pesquisa.
-  Adição de membros ao grupo de pesquisa para indicar os integrantes que compõem o grupo, só será possível adicionar pesquisadores que já se cadastraram no sistema.
